from aoc24 import p08


def test_example_1() -> None:
    lines = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".strip().splitlines()
    grid = p08.parse_input(lines)
    assert grid.count_antinodes(resonant=False) == 14


def test_example_2() -> None:
    lines = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".strip().splitlines()
    grid = p08.parse_input(lines)
    assert grid.count_antinodes(resonant=True) == 34
